- name: Setup logrotate
  become: true
  hosts: all
  tasks:
    - name: Setup logrotate
      ansible.builtin.template:
        src: ../templates/logrotate/ctsms.j2
        dest: /etc/logrotate.d/ctsms
        owner: root
        group: root
        mode: "0644"
